### ISSUE TITLE
error: Could not compile `hpk`

### ISSUE THREAD

**Issue by Grinsel** [nickelc/hpk#13]
what can i do?
pls check my terminal output:

   Compiling hpk v0.3.2 (/home/grinsel/Downloads/hpk)                           
error: Edition 2018 is unstable and only available for nightly builds of rustc. 
                                                                                
error: Could not compile `hpk`.                                                 

To learn more, run the command again with --verbose.
grinsel@ding:~/Downloads/hpk$ cargo build --verbose

   Compiling hpk v0.3.2 (/home/grinsel/Downloads/hpk)                           
     Running `rustc --edition=2018 --crate-name hpk src/hpk/mod.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=d9d205de6e274196 -C extra-filename=-d9d205de6e274196 --out-dir /home/grinsel/Downloads/hpk/target/debug/deps -C incremental=/home/grinsel/Downloads/hpk/target/debug/incremental -L dependency=/home/grinsel/Downloads/hpk/target/debug/deps --extern byteorder=/home/grinsel/Downloads/hpk/target/debug/deps/libbyteorder-988a048c1905d79a.rlib --extern clap=/home/grinsel/Downloads/hpk/target/debug/deps/libclap-1dd52620fc331773.rlib --extern filetime=/home/grinsel/Downloads/hpk/target/debug/deps/libfiletime-3cd8e69c8d1e50d4.rlib --extern flate2=/home/grinsel/Downloads/hpk/target/debug/deps/libflate2-a4dcf890805f6092.rlib --extern glob=/home/grinsel/Downloads/hpk/target/debug/deps/libglob-dfc6ffbad95a9e84.rlib --extern lz4_compress=/home/grinsel/Downloads/hpk/target/debug/deps/liblz4_compress-431422beb68ecad0.rlib --extern nom=/home/grinsel/Downloads/hpk/target/debug/deps/libnom-6b160a556ef528ca.rlib --extern tempfile=/home/grinsel/Downloads/hpk/target/debug/deps/libtempfile-5a6b6bc7620967b1.rlib --extern walkdir=/home/grinsel/Downloads/hpk/target/debug/deps/libwalkdir-4ad7e55a77bda48b.rlib --extern zstd=/home/grinsel/Downloads/hpk/target/debug/deps/libzstd-0fef2881ee8dcbd5.rlib -L native=/home/grinsel/Downloads/hpk/target/debug/build/miniz-sys-24ade8073a23fac7/out -L native=/home/grinsel/Downloads/hpk/target/debug/build/zstd-sys-e586e6dfbfa0abf4/out`
error: Edition 2018 is unstable and only available for nightly builds of rustc. 
                                                                                
error: Could not compile `hpk`.                                                 

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name hpk src/hpk/mod.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=d9d205de6e274196 -C extra-filename=-d9d205de6e274196 --out-dir /home/grinsel/Downloads/hpk/target/debug/deps -C incremental=/home/grinsel/Downloads/hpk/target/debug/incremental -L dependency=/home/grinsel/Downloads/hpk/target/debug/deps --extern byteorder=/home/grinsel/Downloads/hpk/target/debug/deps/libbyteorder-988a048c1905d79a.rlib --extern clap=/home/grinsel/Downloads/hpk/target/debug/deps/libclap-1dd52620fc331773.rlib --extern filetime=/home/grinsel/Downloads/hpk/target/debug/deps/libfiletime-3cd8e69c8d1e50d4.rlib --extern flate2=/home/grinsel/Downloads/hpk/target/debug/deps/libflate2-a4dcf890805f6092.rlib --extern glob=/home/grinsel/Downloads/hpk/target/debug/deps/libglob-dfc6ffbad95a9e84.rlib --extern lz4_compress=/home/grinsel/Downloads/hpk/target/debug/deps/liblz4_compress-431422beb68ecad0.rlib --extern nom=/home/grinsel/Downloads/hpk/target/debug/deps/libnom-6b160a556ef528ca.rlib --extern tempfile=/home/grinsel/Downloads/hpk/target/debug/deps/libtempfile-5a6b6bc7620967b1.rlib --extern walkdir=/home/grinsel/Downloads/hpk/target/debug/deps/libwalkdir-4ad7e55a77bda48b.rlib --extern zstd=/home/grinsel/Downloads/hpk/target/debug/deps/libzstd-0fef2881ee8dcbd5.rlib -L native=/home/grinsel/Downloads/hpk/target/debug/build/miniz-sys-24ade8073a23fac7/out -L native=/home/grinsel/Downloads/hpk/target/debug/build/zstd-sys-e586e6dfbfa0abf4/out` (exit code: 1)

**Comment by nickelc** [comment]
rust 1.31+ is required to compile `master`.
if you can't update rust or use rustup to install the latest stable version of rust then you can checkout the `v0.3.2` tag to compile it.

**Comment by Quix0r** [comment]
1.32.0 here from Debian packages. Still I get compilation errors.

**Comment by Quix0r** [comment]
I hope it worked? Otherwise I have to use my @nextcloud instance to provide you the file.

**Comment by Quix0r** [comment]
@microsoft really messed up @GitHub a lot. :-( https://cloud.mxchange.org/s/public?path=%2Fhpk

**Comment by nickelc** [comment]
> 1.32.0 here from Debian packages. Still I get compilation errors.

hmm, v0.3.2 indeed fails to build now with 1.32.0
v0.3.3 is the first version that comes with Cargo.lock and locked dependencies.

It should work with tag `v0.3.3`
```
hpk on  HEAD (1578ea0) 
> git checkout v0.3.3   
HEAD is now at 1578ea0 v0.3.3

hpk on  HEAD (1578ea0) 
> cargo +1.32.0 c      
    Checking hpk v0.3.3 (/projects/rust/hpk)
    Finished dev [unoptimized + debuginfo] target(s) in 2.27s
```
